### ISSUE TITLE
Demo checklist

### ISSUE THREAD

**Issue by Glazelf** [Glazelf/RiseHax#1]
- [x] Get socket to connect properly
- [x] Read from ram
- [x] Read offset correctly from specific pointer
- [x] Read ram correctly from specific offset
- [x] Write to offset correctly
- [ ] Expand live editing functionalities in preparation of full game
