### ISSUE TITLE
Full game checklist

### ISSUE THREAD

**Issue by Glazelf** [Glazelf/RiseHax#2]
- [ ] Replace demo offsets with (hopefully static) full game offsets
- [ ] Decrypt and document save file(s)
- [ ] Build save editor
